#!/bin/bash -f
cd $( dirname $BASH_SOURCE )

# control chars	    ctcp bold colr undl
ctrl=( $( echo -en '\x01 \x02 \x03 \x1F' ) )
# colous: FFF 000 008 080 F00 844 80F 880 FF0 0F0 088 0FF 00F F0F 888 CCC

# FUNCTIONS

irc(){ echo "$@" >&4 ; }
log(){ [ -n "${@:2}" ] && echo "$( date +%R ) ${@:2}" >> ./logs/$1 ; }

die(){ touch killed ; irc "QUIT :$@" ; }

msg()
{
	case $1 in
	0) irc "PRIVMSG $2 :${@:3}" ;; # normal MSG / PRIVMSG
	1) irc "PRIVMSG $2 :${ctrl[0]}ACTION ${@:3}${ctrl[0]}" ;; # /me
	2) irc "NOTICE $2 :${@:3}" ;; # NOTICE
	3) irc "NOTICE $2 :${ctrl[0]}${@:3}${ctrl[0]}" ;; # CTCP reply
	esac
}

defined(){ declare -f -F $1 ; }

nickname(){ [ -e ./nickname ] && cat ./nickname || die "no nick" ; }

irc_parse ()
{
	case $1 in
		PING) irc "PONG $2" ;;
		ERROR)  exec 4<&-
			[ -e ./killed ] && rm ./killed && exit 0
			exec $BASH_SOURCE $SERVER $PORT
		;;
		*)
			ep=$( expr index "$1" '!' )
			if [ $ep -ne 0 ]; then
				extnick=${1:1:(( ep-=2 ))}
				shift; ( . ./actions ) &
			else
				reply=$2
				shift 3; ( . ./server )
			fi
		;;
	esac
}

[ $# -lt 1 ] && echo "Usage: $BASH_SOURCE server [port]" && exit 1

SERVER=$1; PORT=${2:-6667}

exec 4<> /dev/tcp/$SERVER/$PORT

./date &
trap 'kill $( cat ./date_PID ); rm ./date_PID' EXIT

irc "USER plrin 0 \* :realName"$'\n'"NICK $(nickname)"
while read a; do irc_parse $( tr -d '\n\r' <<< "$a" ) ; done <&4
