#!/bin/bash

echo -n $$ > date_PID

while [ true ]; do
	sleep $(( $( date -d 2359 +%s ) - $( date +%s ) + 50 ))
	until [ "$( date +%H%M )" == "0000" ]; do ( sleep 1 ) ; done
	for a in ./logs/#*; do
		echo "--- Day changed $( date "+%a %d %m %Y" )" >> $a
	done
	sleep 600
done
